server:
  port: 9004
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.114.185.184:3306/yigou?characterEncoding=utf-8
    username: root
    password: 123456
  application:
    name: easygo-ad-service
mybatis:
  mapper-locations: classpath:mapper/*.xml


# 配置Eureka信息
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: easygo-ad-service-9004
